// GENERATED by `flutterfire configure` — project vimes-inventory-doanhdd.
// Android + iOS only.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured for this app.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'FirebaseOptions not configured for $defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpW24mA98B_cXKUHrkbjQwcQWVkvvRGc',
    appId: '1:649130530869:android:ae1bf84ca9460340fbb97c',
    messagingSenderId: '649130530869',
    projectId: 'vimes-inventory-doanhdd',
    storageBucket: 'vimes-inventory-doanhdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm3H6u0aY4-zQozS6pWxJDmTbWJWTh37U',
    appId: '1:649130530869:ios:6abde5b54e001f49fbb97c',
    messagingSenderId: '649130530869',
    projectId: 'vimes-inventory-doanhdd',
    storageBucket: 'vimes-inventory-doanhdd.firebasestorage.app',
    iosBundleId: 'com.doanhdd.vimesInventory',
  );
}
