// Generates lib/firebase_options.dart from the config files downloaded in the
// Firebase Console — no `flutterfire`/`firebase` CLI needed.
//
//   1. Console → Project settings → Your apps
//        Android → download google-services.json  → android/app/google-services.json
//        iOS     → download GoogleService-Info.plist → ios/Runner/GoogleService-Info.plist
//   2. dart run scripts/gen_firebase_options.dart
//
// Web/macOS/Windows are omitted (this app targets android + ios).
import 'dart:convert';
import 'dart:io';

void main() {
  final gs = File('android/app/google-services.json');
  final plist = File('ios/Runner/GoogleService-Info.plist');

  if (!gs.existsSync()) {
    stderr.writeln('Missing android/app/google-services.json');
    exit(1);
  }
  if (!plist.existsSync()) {
    stderr.writeln('Missing ios/Runner/GoogleService-Info.plist');
    exit(1);
  }

  final json = jsonDecode(gs.readAsStringSync()) as Map<String, dynamic>;
  final projectInfo = json['project_info'] as Map<String, dynamic>;
  final projectId = projectInfo['project_id'] as String;
  final messagingSenderId = projectInfo['project_number'] as String;
  final storageBucket = projectInfo['storage_bucket'] as String?;

  final androidClient = (json['client'] as List)
      .cast<Map<String, dynamic>>()
      .first;
  final androidAppId =
      (androidClient['client_info'] as Map)['mobilesdk_app_id'] as String;
  final androidApiKey =
      ((androidClient['api_key'] as List).first as Map)['current_key']
          as String;
  final androidPackage =
      ((androidClient['client_info'] as Map)['android_client_info']
              as Map)['package_name']
          as String;

  final p = _plist(plist.readAsStringSync());
  final iosApiKey = p['API_KEY']!;
  final iosAppId = p['GOOGLE_APP_ID']!;
  final iosBundleId = p['BUNDLE_ID'] ?? androidPackage;

  final out =
      '''
// GENERATED by scripts/gen_firebase_options.dart — do not edit by hand.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'FirebaseOptions not configured for \$defaultTargetPlatform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$androidApiKey',
    appId: '$androidAppId',
    messagingSenderId: '$messagingSenderId',
    projectId: '$projectId',
    storageBucket: '${storageBucket ?? '$projectId.appspot.com'}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '$iosApiKey',
    appId: '$iosAppId',
    messagingSenderId: '$messagingSenderId',
    projectId: '$projectId',
    storageBucket: '${storageBucket ?? '$projectId.appspot.com'}',
    iosBundleId: '$iosBundleId',
  );
}
''';

  File('lib/firebase_options.dart').writeAsStringSync(out);
  stdout.writeln('Wrote lib/firebase_options.dart for project "$projectId".');
}

Map<String, String> _plist(String xml) {
  final map = <String, String>{};
  final re = RegExp(r'<key>([^<]+)</key>\s*<string>([^<]*)</string>');
  for (final m in re.allMatches(xml)) {
    map[m.group(1)!] = m.group(2)!;
  }
  return map;
}
